#!/usr/bin/env bash

if [ "$1" == "static" ]; then
  find -maxdepth 3 -not -path '*/\.*' -not -empty -print |cut -c 3- |tr '/' ' ' |sort |awk 'NF == 3' |tr ' ' '/' | awk -F/ 'BEGIN {printf("%13s | %10s | %33s \n" ,"DISTRO", "VERSION", "INIT COMMAND")} {printf "%13s | %10s | nspawn -i %s/%s/%s\n", $1, $2, $1, $2, $3}' > list.txt
elif [ "$1" == "website" ]; then
  find  -maxdepth 3 -not -path '*/\.*' -not -empty -print |sort|cut -c 3- |tr '/' ' ' |awk 'NF == 3' |tr ' ' '/' | awk -F/ 'BEGIN {printf("| %13s | %10s | %25s | %20s |\n%13s | %10s | %25s | %20s |\n" ,"**Linux Distribution**", "**Version**", "**Init Command**", "**Download Link**", "--------------", "------------", "---------------------------", "--------------------")} {printf "| %13s | %10s | nspawn -i %s/%s/%s | [%s-%s](/storage/%s/%s/%s/image.%s.xz)|\n", toupper(substr($1,1,1))substr($1,2), $2, $1, $2, $3, $1, $3, $1, $2, $3, $3}'
fi
